kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    openshift.io/display-name: ${{ values.name }}
  name: ${{ values.name }}
  namespace: ${{ values.dsp }}
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem